server:
  port: 9999

spring:
  application:
    name: CLIENT-SERVICE
  datasource:
    url: jdbc:h2:mem:clientDb
    driverClassName: org.h2.Driver
    username: client
    password: client
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_URL:http://localhost:8888}/eureka
